service: app2

plugins:
  - serverless-offline

custom:
  serverless-offline:
    dontPrintOutput: true
    port: 3001

provider:
  name: aws
  runtime: nodejs8.10
  region: ap-southeast-2
  environment:
    APP_NAME: ${env:npm_package_name}

functions:
  next:
    handler: lambda.handler
    events:
      - http: ANY /
      - http: ANY {proxy+}   